[passwords]
# SHA256 for "AgenticRules!2026": eec18c5e9e5159f9b69aebcfde8cb449622d113012bacd266cf0bb3378a60581
# You can generate new hashes in Python: hashlib.sha256("your_pass".encode()).hexdigest()
admin = "eec18c5e9e5159f9b69aebcfde8cb449622d113012bacd266cf0bb3378a60581"
